name: Compatibility request
description: Report an incompatibility with another mod
title: '[Compatibility] <title>'
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: The mods
      description: List all mods you want me to add compatibility for here.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add screenshots or descriptions of where your real coords are revelaed, if you want.
